services:
  server:
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}

      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_USERNAME=${MONGO_USERNAME}

      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - DATABASE_URL=${MONGO_HOST}://${MONGO_USERNAME}:${MONGO_PASSWORD}/${MONGO_NAME}?authSource=admin
    depends_on:
      - redis
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command:
      [
        "redis-server",
        "--loglevel warning",
        "--requirepass ${REDIS_PASSWORD}",
      ]
    volumes:
      - redis_data:/data
volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
