services:
  server:
    container_name: ascend-api
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}

      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_USERNAME=${MONGO_USERNAME}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - DATABASE_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/${MONGO_NAME}?authSource=admin
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - redis
      - mongo
  mongo:
    container_name: ascend-mongo
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db
  redis:
    container_name: ascend-redis
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: "redis-server --loglevel warning --appendonly yes --requirepass ${REDIS_PASSWORD}"
    networks:
      - app-network
    volumes:
      - redis_data:/data
volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
networks:
  app-network:
    driver: bridge
